package com.nirvana.community.mapper;

import com.nirvana.community.model.Notification;
import com.nirvana.community.model.User;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface NotificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Wed Feb 05 16:31:34 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Wed Feb 05 16:31:34 CST 2020
     */
    int insert(Notification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Wed Feb 05 16:31:34 CST 2020
     */
    int insertSelective(Notification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Wed Feb 05 16:31:34 CST 2020
     */
    Notification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Wed Feb 05 16:31:34 CST 2020
     */
    int updateByPrimaryKeySelective(Notification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notification
     *
     * @mbggenerated Wed Feb 05 16:31:34 CST 2020
     */
    int updateByPrimaryKey(Notification record);

    /**
     * 根据接受者查询消息
     * @param id
     * @return
     */
    List<Notification> selectByReceiver(Integer id);

    /**
     * 根据接受者修改消息状态
     * @param notification
     */
    void updateStatusByReceiver(Notification notification);
}