package com.nirvana.community.mapper;

import com.nirvana.community.model.Question;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

@Mapper
public interface QuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Mon Dec 02 11:01:57 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Mon Dec 02 11:01:57 CST 2019
     */
    int insert(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Mon Dec 02 11:01:57 CST 2019
     */
    int insertSelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Mon Dec 02 11:01:57 CST 2019
     */
    Question selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Mon Dec 02 11:01:57 CST 2019
     */
    int updateByPrimaryKeySelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Mon Dec 02 11:01:57 CST 2019
     */
    int updateByPrimaryKey(Question record);

    /**
     * 查询所有question
     * @return
     */
    List<Question> selectAllQuestion();

    /**
     * 分页查询
     * @param pageMap
     * @return
     */
    List<Question> selectQuestionByPage(Map<String, Object> pageMap);

    /**
     * 查找问题总数量
     * @return
     */
    Integer selectQuestionCount();

    /**
     * 根据作者查找问题数量
     * @param creator
     * @return
     */
    Integer selectQuestionCountByCreator(Integer creator);
}