package com.nirvana.community.mapper;

import com.nirvana.community.model.User;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Dec 02 11:01:57 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Dec 02 11:01:57 CST 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Mon Dec 02 11:01:57 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Mon Dec 02 11:01:57 CST 2019
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Mon Dec 02 11:01:57 CST 2019
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated Mon Dec 02 11:01:57 CST 2019
     */
    int updateByPrimaryKey(User record);

    /**
     * 根据token查询用户
     * @param token
     * @return
     */
    User selectUserByToken(String token);

    /**
     * 根据账户id查询用户
     * @param id
     * @return
     */
    User selectByAccountId(String id);

    /**
     * 根据用户名查询用户
     * @param name
     * @return
     */
    User selectByName(String name);

    /**
     * 根据用户名密码判断用户是否输入正确
     * @param user
     * @return
     */
    User selectByNameAndPassword(User user);
}